name: Pull Request Auto Update

on:
  push: {}

jobs:

  # Auto update PR if target branch is updated
  auto-update:
   name: auto-update
   runs-on: ubuntu-latest
   steps:
    - uses: docker://chinthakagodawita/autoupdate-action:v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
