# Runs jobs to update a newly created pull request

name: Pull Request Updater

on: pull_request

jobs:

  # Automatically assign a size label to the pr
  label_size:
    runs-on: ubuntu-latest
    steps:
    - uses: CodelyTV/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_max_size: '10'
        s_max_size: '100'
        m_max_size: '500'
        l_max_size: '1000'
        fail_if_xl: 'false'


  # Automatically assign labels based on code content
  label_content:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Content Labeler
        uses: Decathlon/pull-request-labeler-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
