# Runs jobs to update a newly created pull request

name: Pull Request Updater

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:

  # Automatically assign labels based on code content
  label_content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: banyan/auto-label@1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
